In [12]:
from ipywidgets import interact
import ipywidgets as widgets
from sqlalchemy import create_engine
import pandas as pd

In [13]:
%load_ext sql

engine = create_engine('postgresql://postgres:pgadmin@localhost:5432/postgres')
%sql postgresql://postgres:pgadmin@localhost:5432/postgres

The sql extension is already loaded. To reload it, use:
  %reload_ext sql

In [14]:
%%sql
SELECT Current_database();

 * postgresql://postgres:***@localhost:5432/postgres
1 rows affected.

[('postgres',)]

## Carregando os CSVs

In [15]:
df_calendar = pd.read_csv('csv/calendar.csv')
df_calendar

,listing_id,date,available,price,adjusted_price,minimum_nights,maximum_nights
0,17878,2023-12-27,f,$350.00,NaN,5.0,28.0
1,17878,2023-12-28,f,$350.00,NaN,5.0,28.0
2,17878,2023-12-29,f,$350.00,NaN,5.0,28.0
3,17878,2023-12-30,f,$350.00,NaN,5.0,28.0
4,17878,2023-12-31,f,$350.00,NaN,5.0,28.0
...,...,...,...,...,...,...,...
13145590,1053155096258508813,2024-12-20,f,$250.00,NaN,3.0,7.0
13145591,1053155096258508813,2024-12-21,f,$250.00,NaN,3.0,7.0
13145592,1053155096258508813,2024-12-22,f,$250.00,NaN,3.0,7.0
13145593,1053155096258508813,2024-12-23,f,$250.00,NaN,3.0,7.0
13145594,1053155096258508813,2024-12-24,f,$250.00,NaN,3.0,7.0

In [16]:
df_listings = pd.read_csv('csv/listings.csv')
df_listings

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license
0,17878,Condo in Rio de Janeiro · ★4.70 · 2 bedrooms ·...,68997,Matthias,NaN,Copacabana,-22.965990,-43.179400,Entire home/apt,1357.0,5,311,2023-12-22,1.90,1,269,29,NaN
1,216461,Rental unit in Rio de Janeiro · 1 bedroom · 1 ...,1154263,"Zeilma , Da",NaN,Flamengo,-22.939900,-43.176760,Private room,734.0,1,0,NaN,NaN,1,365,0,NaN
2,326205,Condo in Rio de Janeiro · ★4.57 · 1 bedroom · ...,1603206,Bob,NaN,Copacabana,-22.968250,-43.182370,Entire home/apt,366.0,3,152,2023-11-21,1.07,5,293,14,NaN
3,25026,Rental unit in Rio de Janeiro · ★4.72 · 1 bedr...,102840,Viviane,NaN,Copacabana,-22.977350,-43.191050,Entire home/apt,865.0,2,275,2023-12-03,1.67,1,228,29,NaN
4,326575,Rental unit in Rio de Janeiro · ★4.81 · 2 bedr...,1668565,Maria José,NaN,Copacabana,-22.976960,-43.189330,Entire home/apt,368.0,4,227,2023-11-21,1.58,1,245,12,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36003,1053746406056980189,Home in Rio de Janeiro · ★New · 1 bedroom · 4 ...,470173166,Marco,NaN,Botafogo,-22.956393,-43.182119,Private room,200.0,2,0,NaN,NaN,8,90,0,NaN
36004,1053756202332288557,Rental unit in Rio de Janeiro · ★New · 1 bedro...,6000862,Omar Do Rio,NaN,Copacabana,-22.980547,-43.195863,Entire home/apt,727.0,2,0,NaN,NaN,185,358,0,NaN
36005,1053789340172837654,Rental unit in Rio de Janeiro · ★New · 1 bedro...,206898000,Pablo,NaN,Copacabana,-22.968340,-43.185855,Private room,743.0,1,0,NaN,NaN,1,270,0,NaN
36006,1053808194231554793,Rental unit in Rio de Janeiro · ★New · 1 bedro...,536983374,Izaias,NaN,Vidigal,-22.996260,-43.240830,Entire home/apt,560.0,1,0,NaN,NaN,1,249,0,NaN
36007,1053823261878675052,Rental unit in Rio de Janeiro · ★New · 1 bedro...,694816,Samuel,NaN,Glória,-22.912241,-43.171288,Private room,175.0,2,0,NaN,NaN,1,19,0,NaN

In [17]:
df_reviews = pd.read_csv('csv/reviews.csv')
df_reviews

,listing_id,id,date,reviewer_id,reviewer_name,comments
0,17878,64852,2010-07-15,135370,Tia,This apartment is in a perfect location -- two...
1,216700,1511171,2012-06-18,2598011,Evelyn,"A estada foi maravilhosa, ficamos so 3 noites ..."
2,216700,1550596,2012-06-24,2465739,Camila,The apartment is located in the beautiful Lara...
3,17878,76744,2010-08-11,10206,Mimi,we had a really great experience staying in Ma...
4,17878,91074,2010-09-06,80253,Jan,Staying in Max appartment is like living in a ...
...,...,...,...,...,...,...
703791,1053655074004481557,1055764873322213198,2023-12-27,523745376,Adriana,"Apartamento top! Super novo, limpinho, todo eq..."
703792,1053716797020259779,1054357802054468817,2023-12-25,488321805,Juliana,Passamos dias maravilhosos aqui! A vista é sim...
703793,1053716797020259779,1055794588292689437,2023-12-27,206634401,Victor,Excelente anfitrião! Super atencioso e cortês!...
703794,1050572397352975357,1055147776405273833,2023-12-26,257578099,Dominiky,"Li preparou tudo e nós recebeu muito bem, com ..."
703795,1052351794224065415,1053610730723650852,2023-12-24,546368460,Cicera,"Amei o apartamento. A decoração esta linda, tu..."

In [18]:
# Ajustando o price para ser float
df_calendar['price'] = df_calendar['price'].str.replace('$', '').str.replace(',', '').astype(float)
df_listings['price'] = df_listings['price'].replace('[\$,]', '', regex=True).astype(float)

/tmp/ipykernel_814/2156717546.py:2: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df_calendar['price'] = df_calendar['price'].str.replace('$', '').str.replace(',', '').astype(float)

In [19]:
# Antes de criar as tabelas validar se os campos pensados podem ser chave
#calendar.csv
print(f" Tem listing_id e date repetido no csv calendar.csv: {df_calendar.duplicated(subset=['listing_id', 'date']).any()}")
#listings.csv
print(f" Tem id repetido no csv listings.csv:                {df_listings['id'].duplicated().any()}")
#reviews.csv
print(f" Tem id repetido no csv reviews.csv:                 {df_reviews['id'].duplicated().any()}")

 Tem listing_id e date repetido no csv calendar.csv: False
 Tem id repetido no csv listings.csv:                False
 Tem id repetido no csv reviews.csv:                 False

## Criando as tabelas

In [20]:
%%sql
CREATE TABLE IF NOT EXISTS Calendar (
    listing_id INT,
    date DATE,
    available BOOLEAN,
    price DECIMAL(10, 2),
    adjusted_price DECIMAL(10, 2),
    minimum_nights INT,
    maximum_nights INT,
    PRIMARY KEY (listing_id, date)
);

 * postgresql://postgres:***@localhost:5432/postgres
Done.

[]

In [21]:
%%sql

CREATE TABLE IF NOT EXISTS Reviews (
    id BIGINT PRIMARY KEY,
    listing_id BIGINT,
    date DATE,
    reviewer_id BIGINT,
    reviewer_name VARCHAR(255),
    comments TEXT
);

 * postgresql://postgres:***@localhost:5432/postgres
Done.

[]

In [22]:
%%sql
CREATE TABLE IF NOT EXISTS Listings (
    id INT PRIMARY KEY,
    name VARCHAR(255),
    host_id INT,
    host_name VARCHAR(255),
    neighbourhood_group VARCHAR(100),
    neighbourhood VARCHAR(100),
    latitude DECIMAL(10, 6),
    longitude DECIMAL(10, 6),
    room_type VARCHAR(100),
    price DECIMAL(10, 2),
    minimum_nights INT,
    number_of_reviews INT,
    last_review DATE,
    reviews_per_month DECIMAL(6, 2),
    calculated_host_listings_count INT,
    availability_365 INT,
    number_of_reviews_ltm INT,
    license VARCHAR(100)
);

 * postgresql://postgres:***@localhost:5432/postgres
Done.

[]

## Populando as tabelas

OBS: Por questão de desempenho da máquina local, foi escolhido popular apenas as 100 primeiras linhas de cada DF

In [23]:
df_calendar_table = df_calendar.head(100)
df_calendar_table.to_sql('calendar', con=engine, if_exists='append', index=False, method='multi')

IntegrityError: (psycopg2.errors.UniqueViolation) ERRO:  duplicar valor da chave viola a restrição de unicidade "calendar_pkey"
DETAIL:  Chave (listing_id, date)=(17878, 2023-12-27) já existe.

[SQL: INSERT INTO calendar (listing_id, date, available, price, adjusted_price, minimum_nights, maximum_nights) VALUES (%(listing_id_m0)s, %(date_m0)s, %(available_m0)s, %(price_m0)s, %(adjusted_price_m0)s, %(minimum_nights_m0)s, %(maximum_nights_m0)s), (%(listing_id_m1)s, %(date_m1)s, %(available_m1)s, %(price_m1)s, %(adjusted_price_m1)s, %(minimum_nights_m1)s, %(maximum_nights_m1)s), (%(listing_id_m2)s, %(date_m2)s, %(available_m2)s, %(price_m2)s, %(adjusted_price_m2)s, %(minimum_nights_m2)s, %(maximum_nights_m2)s), (%(listing_id_m3)s, %(date_m3)s, %(available_m3)s, %(price_m3)s, %(adjusted_price_m3)s, %(minimum_nights_m3)s, %(maximum_nights_m3)s), (%(listing_id_m4)s, %(date_m4)s, %(available_m4)s, %(price_m4)s, %(adjusted_price_m4)s, %(minimum_nights_m4)s, %(maximum_nights_m4)s), (%(listing_id_m5)s, %(date_m5)s, %(available_m5)s, %(price_m5)s, %(adjusted_price_m5)s, %(minimum_nights_m5)s, %(maximum_nights_m5)s), (%(listing_id_m6)s, %(date_m6)s, %(available_m6)s, %(price_m6)s, %(adjusted_price_m6)s, %(minimum_nights_m6)s, %(maximum_nights_m6)s), (%(listing_id_m7)s, %(date_m7)s, %(available_m7)s, %(price_m7)s, %(adjusted_price_m7)s, %(minimum_nights_m7)s, %(maximum_nights_m7)s), (%(listing_id_m8)s, %(date_m8)s, %(available_m8)s, %(price_m8)s, %(adjusted_price_m8)s, %(minimum_nights_m8)s, %(maximum_nights_m8)s), (%(listing_id_m9)s, %(date_m9)s, %(available_m9)s, %(price_m9)s, %(adjusted_price_m9)s, %(minimum_nights_m9)s, %(maximum_nights_m9)s), (%(listing_id_m10)s, %(date_m10)s, %(available_m10)s, %(price_m10)s, %(adjusted_price_m10)s, %(minimum_nights_m10)s, %(maximum_nights_m10)s), (%(listing_id_m11)s, %(date_m11)s, %(available_m11)s, %(price_m11)s, %(adjusted_price_m11)s, %(minimum_nights_m11)s, %(maximum_nights_m11)s), (%(listing_id_m12)s, %(date_m12)s, %(available_m12)s, %(price_m12)s, %(adjusted_price_m12)s, %(minimum_nights_m12)s, %(maximum_nights_m12)s), (%(listing_id_m13)s, %(date_m13)s, %(available_m13)s, %(price_m13)s, %(adjusted_price_m13)s, %(minimum_nights_m13)s, %(maximum_nights_m13)s), (%(listing_id_m14)s, %(date_m14)s, %(available_m14)s, %(price_m14)s, %(adjusted_price_m14)s, %(minimum_nights_m14)s, %(maximum_nights_m14)s), (%(listing_id_m15)s, %(date_m15)s, %(available_m15)s, %(price_m15)s, %(adjusted_price_m15)s, %(minimum_nights_m15)s, %(maximum_nights_m15)s), (%(listing_id_m16)s, %(date_m16)s, %(available_m16)s, %(price_m16)s, %(adjusted_price_m16)s, %(minimum_nights_m16)s, %(maximum_nights_m16)s), (%(listing_id_m17)s, %(date_m17)s, %(available_m17)s, %(price_m17)s, %(adjusted_price_m17)s, %(minimum_nights_m17)s, %(maximum_nights_m17)s), (%(listing_id_m18)s, %(date_m18)s, %(available_m18)s, %(price_m18)s, %(adjusted_price_m18)s, %(minimum_nights_m18)s, %(maximum_nights_m18)s), (%(listing_id_m19)s, %(date_m19)s, %(available_m19)s, %(price_m19)s, %(adjusted_price_m19)s, %(minimum_nights_m19)s, %(maximum_nights_m19)s), (%(listing_id_m20)s, %(date_m20)s, %(available_m20)s, %(price_m20)s, %(adjusted_price_m20)s, %(minimum_nights_m20)s, %(maximum_nights_m20)s), (%(listing_id_m21)s, %(date_m21)s, %(available_m21)s, %(price_m21)s, %(adjusted_price_m21)s, %(minimum_nights_m21)s, %(maximum_nights_m21)s), (%(listing_id_m22)s, %(date_m22)s, %(available_m22)s, %(price_m22)s, %(adjusted_price_m22)s, %(minimum_nights_m22)s, %(maximum_nights_m22)s), (%(listing_id_m23)s, %(date_m23)s, %(available_m23)s, %(price_m23)s, %(adjusted_price_m23)s, %(minimum_nights_m23)s, %(maximum_nights_m23)s), (%(listing_id_m24)s, %(date_m24)s, %(available_m24)s, %(price_m24)s, %(adjusted_price_m24)s, %(minimum_nights_m24)s, %(maximum_nights_m24)s), (%(listing_id_m25)s, %(date_m25)s, %(available_m25)s, %(price_m25)s, %(adjusted_price_m25)s, %(minimum_nights_m25)s, %(maximum_nights_m25)s), (%(listing_id_m26)s, %(date_m26)s, %(available_m26)s, %(price_m26)s, %(adjusted_price_m26)s, %(minimum_nights_m26)s, %(maximum_nights_m26)s), (%(listing_id_m27)s, %(date_m27)s, %(available_m27)s, %(price_m27)s, %(adjusted_price_m27)s, %(minimum_nights_m27)s, %(maximum_nights_m27)s), (%(listing_id_m28)s, %(date_m28)s, %(available_m28)s, %(price_m28)s, %(adjusted_price_m28)s, %(minimum_nights_m28)s, %(maximum_nights_m28)s), (%(listing_id_m29)s, %(date_m29)s, %(available_m29)s, %(price_m29)s, %(adjusted_price_m29)s, %(minimum_nights_m29)s, %(maximum_nights_m29)s), (%(listing_id_m30)s, %(date_m30)s, %(available_m30)s, %(price_m30)s, %(adjusted_price_m30)s, %(minimum_nights_m30)s, %(maximum_nights_m30)s), (%(listing_id_m31)s, %(date_m31)s, %(available_m31)s, %(price_m31)s, %(adjusted_price_m31)s, %(minimum_nights_m31)s, %(maximum_nights_m31)s), (%(listing_id_m32)s, %(date_m32)s, %(available_m32)s, %(price_m32)s, %(adjusted_price_m32)s, %(minimum_nights_m32)s, %(maximum_nights_m32)s), (%(listing_id_m33)s, %(date_m33)s, %(available_m33)s, %(price_m33)s, %(adjusted_price_m33)s, %(minimum_nights_m33)s, %(maximum_nights_m33)s), (%(listing_id_m34)s, %(date_m34)s, %(available_m34)s, %(price_m34)s, %(adjusted_price_m34)s, %(minimum_nights_m34)s, %(maximum_nights_m34)s), (%(listing_id_m35)s, %(date_m35)s, %(available_m35)s, %(price_m35)s, %(adjusted_price_m35)s, %(minimum_nights_m35)s, %(maximum_nights_m35)s), (%(listing_id_m36)s, %(date_m36)s, %(available_m36)s, %(price_m36)s, %(adjusted_price_m36)s, %(minimum_nights_m36)s, %(maximum_nights_m36)s), (%(listing_id_m37)s, %(date_m37)s, %(available_m37)s, %(price_m37)s, %(adjusted_price_m37)s, %(minimum_nights_m37)s, %(maximum_nights_m37)s), (%(listing_id_m38)s, %(date_m38)s, %(available_m38)s, %(price_m38)s, %(adjusted_price_m38)s, %(minimum_nights_m38)s, %(maximum_nights_m38)s), (%(listing_id_m39)s, %(date_m39)s, %(available_m39)s, %(price_m39)s, %(adjusted_price_m39)s, %(minimum_nights_m39)s, %(maximum_nights_m39)s), (%(listing_id_m40)s, %(date_m40)s, %(available_m40)s, %(price_m40)s, %(adjusted_price_m40)s, %(minimum_nights_m40)s, %(maximum_nights_m40)s), (%(listing_id_m41)s, %(date_m41)s, %(available_m41)s, %(price_m41)s, %(adjusted_price_m41)s, %(minimum_nights_m41)s, %(maximum_nights_m41)s), (%(listing_id_m42)s, %(date_m42)s, %(available_m42)s, %(price_m42)s, %(adjusted_price_m42)s, %(minimum_nights_m42)s, %(maximum_nights_m42)s), (%(listing_id_m43)s, %(date_m43)s, %(available_m43)s, %(price_m43)s, %(adjusted_price_m43)s, %(minimum_nights_m43)s, %(maximum_nights_m43)s), (%(listing_id_m44)s, %(date_m44)s, %(available_m44)s, %(price_m44)s, %(adjusted_price_m44)s, %(minimum_nights_m44)s, %(maximum_nights_m44)s), (%(listing_id_m45)s, %(date_m45)s, %(available_m45)s, %(price_m45)s, %(adjusted_price_m45)s, %(minimum_nights_m45)s, %(maximum_nights_m45)s), (%(listing_id_m46)s, %(date_m46)s, %(available_m46)s, %(price_m46)s, %(adjusted_price_m46)s, %(minimum_nights_m46)s, %(maximum_nights_m46)s), (%(listing_id_m47)s, %(date_m47)s, %(available_m47)s, %(price_m47)s, %(adjusted_price_m47)s, %(minimum_nights_m47)s, %(maximum_nights_m47)s), (%(listing_id_m48)s, %(date_m48)s, %(available_m48)s, %(price_m48)s, %(adjusted_price_m48)s, %(minimum_nights_m48)s, %(maximum_nights_m48)s), (%(listing_id_m49)s, %(date_m49)s, %(available_m49)s, %(price_m49)s, %(adjusted_price_m49)s, %(minimum_nights_m49)s, %(maximum_nights_m49)s), (%(listing_id_m50)s, %(date_m50)s, %(available_m50)s, %(price_m50)s, %(adjusted_price_m50)s, %(minimum_nights_m50)s, %(maximum_nights_m50)s), (%(listing_id_m51)s, %(date_m51)s, %(available_m51)s, %(price_m51)s, %(adjusted_price_m51)s, %(minimum_nights_m51)s, %(maximum_nights_m51)s), (%(listing_id_m52)s, %(date_m52)s, %(available_m52)s, %(price_m52)s, %(adjusted_price_m52)s, %(minimum_nights_m52)s, %(maximum_nights_m52)s), (%(listing_id_m53)s, %(date_m53)s, %(available_m53)s, %(price_m53)s, %(adjusted_price_m53)s, %(minimum_nights_m53)s, %(maximum_nights_m53)s), (%(listing_id_m54)s, %(date_m54)s, %(available_m54)s, %(price_m54)s, %(adjusted_price_m54)s, %(minimum_nights_m54)s, %(maximum_nights_m54)s), (%(listing_id_m55)s, %(date_m55)s, %(available_m55)s, %(price_m55)s, %(adjusted_price_m55)s, %(minimum_nights_m55)s, %(maximum_nights_m55)s), (%(listing_id_m56)s, %(date_m56)s, %(available_m56)s, %(price_m56)s, %(adjusted_price_m56)s, %(minimum_nights_m56)s, %(maximum_nights_m56)s), (%(listing_id_m57)s, %(date_m57)s, %(available_m57)s, %(price_m57)s, %(adjusted_price_m57)s, %(minimum_nights_m57)s, %(maximum_nights_m57)s), (%(listing_id_m58)s, %(date_m58)s, %(available_m58)s, %(price_m58)s, %(adjusted_price_m58)s, %(minimum_nights_m58)s, %(maximum_nights_m58)s), (%(listing_id_m59)s, %(date_m59)s, %(available_m59)s, %(price_m59)s, %(adjusted_price_m59)s, %(minimum_nights_m59)s, %(maximum_nights_m59)s), (%(listing_id_m60)s, %(date_m60)s, %(available_m60)s, %(price_m60)s, %(adjusted_price_m60)s, %(minimum_nights_m60)s, %(maximum_nights_m60)s), (%(listing_id_m61)s, %(date_m61)s, %(available_m61)s, %(price_m61)s, %(adjusted_price_m61)s, %(minimum_nights_m61)s, %(maximum_nights_m61)s), (%(listing_id_m62)s, %(date_m62)s, %(available_m62)s, %(price_m62)s, %(adjusted_price_m62)s, %(minimum_nights_m62)s, %(maximum_nights_m62)s), (%(listing_id_m63)s, %(date_m63)s, %(available_m63)s, %(price_m63)s, %(adjusted_price_m63)s, %(minimum_nights_m63)s, %(maximum_nights_m63)s), (%(listing_id_m64)s, %(date_m64)s, %(available_m64)s, %(price_m64)s, %(adjusted_price_m64)s, %(minimum_nights_m64)s, %(maximum_nights_m64)s), (%(listing_id_m65)s, %(date_m65)s, %(available_m65)s, %(price_m65)s, %(adjusted_price_m65)s, %(minimum_nights_m65)s, %(maximum_nights_m65)s), (%(listing_id_m66)s, %(date_m66)s, %(available_m66)s, %(price_m66)s, %(adjusted_price_m66)s, %(minimum_nights_m66)s, %(maximum_nights_m66)s), (%(listing_id_m67)s, %(date_m67)s, %(available_m67)s, %(price_m67)s, %(adjusted_price_m67)s, %(minimum_nights_m67)s, %(maximum_nights_m67)s), (%(listing_id_m68)s, %(date_m68)s, %(available_m68)s, %(price_m68)s, %(adjusted_price_m68)s, %(minimum_nights_m68)s, %(maximum_nights_m68)s), (%(listing_id_m69)s, %(date_m69)s, %(available_m69)s, %(price_m69)s, %(adjusted_price_m69)s, %(minimum_nights_m69)s, %(maximum_nights_m69)s), (%(listing_id_m70)s, %(date_m70)s, %(available_m70)s, %(price_m70)s, %(adjusted_price_m70)s, %(minimum_nights_m70)s, %(maximum_nights_m70)s), (%(listing_id_m71)s, %(date_m71)s, %(available_m71)s, %(price_m71)s, %(adjusted_price_m71)s, %(minimum_nights_m71)s, %(maximum_nights_m71)s), (%(listing_id_m72)s, %(date_m72)s, %(available_m72)s, %(price_m72)s, %(adjusted_price_m72)s, %(minimum_nights_m72)s, %(maximum_nights_m72)s), (%(listing_id_m73)s, %(date_m73)s, %(available_m73)s, %(price_m73)s, %(adjusted_price_m73)s, %(minimum_nights_m73)s, %(maximum_nights_m73)s), (%(listing_id_m74)s, %(date_m74)s, %(available_m74)s, %(price_m74)s, %(adjusted_price_m74)s, %(minimum_nights_m74)s, %(maximum_nights_m74)s), (%(listing_id_m75)s, %(date_m75)s, %(available_m75)s, %(price_m75)s, %(adjusted_price_m75)s, %(minimum_nights_m75)s, %(maximum_nights_m75)s), (%(listing_id_m76)s, %(date_m76)s, %(available_m76)s, %(price_m76)s, %(adjusted_price_m76)s, %(minimum_nights_m76)s, %(maximum_nights_m76)s), (%(listing_id_m77)s, %(date_m77)s, %(available_m77)s, %(price_m77)s, %(adjusted_price_m77)s, %(minimum_nights_m77)s, %(maximum_nights_m77)s), (%(listing_id_m78)s, %(date_m78)s, %(available_m78)s, %(price_m78)s, %(adjusted_price_m78)s, %(minimum_nights_m78)s, %(maximum_nights_m78)s), (%(listing_id_m79)s, %(date_m79)s, %(available_m79)s, %(price_m79)s, %(adjusted_price_m79)s, %(minimum_nights_m79)s, %(maximum_nights_m79)s), (%(listing_id_m80)s, %(date_m80)s, %(available_m80)s, %(price_m80)s, %(adjusted_price_m80)s, %(minimum_nights_m80)s, %(maximum_nights_m80)s), (%(listing_id_m81)s, %(date_m81)s, %(available_m81)s, %(price_m81)s, %(adjusted_price_m81)s, %(minimum_nights_m81)s, %(maximum_nights_m81)s), (%(listing_id_m82)s, %(date_m82)s, %(available_m82)s, %(price_m82)s, %(adjusted_price_m82)s, %(minimum_nights_m82)s, %(maximum_nights_m82)s), (%(listing_id_m83)s, %(date_m83)s, %(available_m83)s, %(price_m83)s, %(adjusted_price_m83)s, %(minimum_nights_m83)s, %(maximum_nights_m83)s), (%(listing_id_m84)s, %(date_m84)s, %(available_m84)s, %(price_m84)s, %(adjusted_price_m84)s, %(minimum_nights_m84)s, %(maximum_nights_m84)s), (%(listing_id_m85)s, %(date_m85)s, %(available_m85)s, %(price_m85)s, %(adjusted_price_m85)s, %(minimum_nights_m85)s, %(maximum_nights_m85)s), (%(listing_id_m86)s, %(date_m86)s, %(available_m86)s, %(price_m86)s, %(adjusted_price_m86)s, %(minimum_nights_m86)s, %(maximum_nights_m86)s), (%(listing_id_m87)s, %(date_m87)s, %(available_m87)s, %(price_m87)s, %(adjusted_price_m87)s, %(minimum_nights_m87)s, %(maximum_nights_m87)s), (%(listing_id_m88)s, %(date_m88)s, %(available_m88)s, %(price_m88)s, %(adjusted_price_m88)s, %(minimum_nights_m88)s, %(maximum_nights_m88)s), (%(listing_id_m89)s, %(date_m89)s, %(available_m89)s, %(price_m89)s, %(adjusted_price_m89)s, %(minimum_nights_m89)s, %(maximum_nights_m89)s), (%(listing_id_m90)s, %(date_m90)s, %(available_m90)s, %(price_m90)s, %(adjusted_price_m90)s, %(minimum_nights_m90)s, %(maximum_nights_m90)s), (%(listing_id_m91)s, %(date_m91)s, %(available_m91)s, %(price_m91)s, %(adjusted_price_m91)s, %(minimum_nights_m91)s, %(maximum_nights_m91)s), (%(listing_id_m92)s, %(date_m92)s, %(available_m92)s, %(price_m92)s, %(adjusted_price_m92)s, %(minimum_nights_m92)s, %(maximum_nights_m92)s), (%(listing_id_m93)s, %(date_m93)s, %(available_m93)s, %(price_m93)s, %(adjusted_price_m93)s, %(minimum_nights_m93)s, %(maximum_nights_m93)s), (%(listing_id_m94)s, %(date_m94)s, %(available_m94)s, %(price_m94)s, %(adjusted_price_m94)s, %(minimum_nights_m94)s, %(maximum_nights_m94)s), (%(listing_id_m95)s, %(date_m95)s, %(available_m95)s, %(price_m95)s, %(adjusted_price_m95)s, %(minimum_nights_m95)s, %(maximum_nights_m95)s), (%(listing_id_m96)s, %(date_m96)s, %(available_m96)s, %(price_m96)s, %(adjusted_price_m96)s, %(minimum_nights_m96)s, %(maximum_nights_m96)s), (%(listing_id_m97)s, %(date_m97)s, %(available_m97)s, %(price_m97)s, %(adjusted_price_m97)s, %(minimum_nights_m97)s, %(maximum_nights_m97)s), (%(listing_id_m98)s, %(date_m98)s, %(available_m98)s, %(price_m98)s, %(adjusted_price_m98)s, %(minimum_nights_m98)s, %(maximum_nights_m98)s), (%(listing_id_m99)s, %(date_m99)s, %(available_m99)s, %(price_m99)s, %(adjusted_price_m99)s, %(minimum_nights_m99)s, %(maximum_nights_m99)s)]
[parameters: {'listing_id_m0': 17878, 'date_m0': '2023-12-27', 'available_m0': 'f', 'price_m0': 350.0, 'adjusted_price_m0': None, 'minimum_nights_m0': 5.0, 'maximum_nights_m0': 28.0, 'listing_id_m1': 17878, 'date_m1': '2023-12-28', 'available_m1': 'f', 'price_m1': 350.0, 'adjusted_price_m1': None, 'minimum_nights_m1': 5.0, 'maximum_nights_m1': 28.0, 'listing_id_m2': 17878, 'date_m2': '2023-12-29', 'available_m2': 'f', 'price_m2': 350.0, 'adjusted_price_m2': None, 'minimum_nights_m2': 5.0, 'maximum_nights_m2': 28.0, 'listing_id_m3': 17878, 'date_m3': '2023-12-30', 'available_m3': 'f', 'price_m3': 350.0, 'adjusted_price_m3': None, 'minimum_nights_m3': 5.0, 'maximum_nights_m3': 28.0, 'listing_id_m4': 17878, 'date_m4': '2023-12-31', 'available_m4': 'f', 'price_m4': 350.0, 'adjusted_price_m4': None, 'minimum_nights_m4': 5.0, 'maximum_nights_m4': 28.0, 'listing_id_m5': 17878, 'date_m5': '2024-01-01', 'available_m5': 'f', 'price_m5': 350.0, 'adjusted_price_m5': None, 'minimum_nights_m5': 5.0, 'maximum_nights_m5': 28.0, 'listing_id_m6': 17878, 'date_m6': '2024-01-02', 'available_m6': 'f', 'price_m6': 350.0, 'adjusted_price_m6': None, 'minimum_nights_m6': 5.0, 'maximum_nights_m6': 28.0, 'listing_id_m7': 17878 ... 600 parameters truncated ... 'maximum_nights_m92': 28.0, 'listing_id_m93': 17878, 'date_m93': '2024-03-29', 'available_m93': 'f', 'price_m93': 350.0, 'adjusted_price_m93': None, 'minimum_nights_m93': 5.0, 'maximum_nights_m93': 28.0, 'listing_id_m94': 17878, 'date_m94': '2024-03-30', 'available_m94': 'f', 'price_m94': 350.0, 'adjusted_price_m94': None, 'minimum_nights_m94': 5.0, 'maximum_nights_m94': 28.0, 'listing_id_m95': 17878, 'date_m95': '2024-03-31', 'available_m95': 'f', 'price_m95': 350.0, 'adjusted_price_m95': None, 'minimum_nights_m95': 5.0, 'maximum_nights_m95': 28.0, 'listing_id_m96': 17878, 'date_m96': '2024-04-01', 'available_m96': 'f', 'price_m96': 350.0, 'adjusted_price_m96': None, 'minimum_nights_m96': 5.0, 'maximum_nights_m96': 28.0, 'listing_id_m97': 17878, 'date_m97': '2024-04-02', 'available_m97': 'f', 'price_m97': 350.0, 'adjusted_price_m97': None, 'minimum_nights_m97': 5.0, 'maximum_nights_m97': 28.0, 'listing_id_m98': 17878, 'date_m98': '2024-04-03', 'available_m98': 'f', 'price_m98': 350.0, 'adjusted_price_m98': None, 'minimum_nights_m98': 5.0, 'maximum_nights_m98': 28.0, 'listing_id_m99': 17878, 'date_m99': '2024-04-04', 'available_m99': 'f', 'price_m99': 350.0, 'adjusted_price_m99': None, 'minimum_nights_m99': 5.0, 'maximum_nights_m99': 28.0}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)

In [24]:
%%sql
SELECT * FROM calendar LIMIT 15;

 * postgresql://postgres:***@localhost:5432/postgres
15 rows affected.

[(17878, datetime.date(2023, 12, 27), False, '350.0', None, 5, 28),
 (17878, datetime.date(2023, 12, 28), False, '350.0', None, 5, 28),
 (17878, datetime.date(2023, 12, 29), False, '350.0', None, 5, 28),
 (17878, datetime.date(2023, 12, 30), False, '350.0', None, 5, 28),
 (17878, datetime.date(2023, 12, 31), False, '350.0', None, 5, 28),
 (17878, datetime.date(2024, 1, 1), False, '350.0', None, 5, 28),
 (17878, datetime.date(2024, 1, 2), False, '350.0', None, 5, 28),
 (17878, datetime.date(2024, 1, 3), False, '350.0', None, 5, 28),
 (17878, datetime.date(2024, 1, 4), False, '350.0', None, 5, 28),
 (17878, datetime.date(2024, 1, 5), True, '350.0', None, 5, 28),
 (17878, datetime.date(2024, 1, 6), True, '350.0', None, 5, 28),
 (17878, datetime.date(2024, 1, 7), False, '350.0', None, 5, 28),
 (17878, datetime.date(2024, 1, 8), False, '350.0', None, 5, 28),
 (17878, datetime.date(2024, 1, 9), False, '350.0', None, 5, 28),
 (17878, datetime.date(2024, 1, 10), False, '350.0', None, 5, 28)]

In [ ]:
%%sql
TRUNCATE TABLE reviews

 * postgresql://postgres:***@localhost:5432/postgres
Done.

[]

In [ ]:
df_reviews_table = df_reviews.head(100)
df_reviews_table.to_sql('reviews', con=engine, if_exists='append', index=False, method='multi')

100

In [ ]:
%%sql
SELECT * FROM reviews LIMIT 15;

 * postgresql://postgres:***@localhost:5432/postgres
15 rows affected.

[(64852, 17878, datetime.date(2010, 7, 15), 135370, 'Tia', 'This apartment is in a perfect location -- two blocks from the beach and two blocks from the Copacabana Palace (where anyone famous stays when they a ... (99 characters truncated) ... e apartment is like, so you´ll have no surprises.  Max is very communicative and helpful.  The four of us that stayed here would highly recommend it.'),
 (1511171, 216700, datetime.date(2012, 6, 18), 2598011, 'Evelyn', 'A estada foi maravilhosa, ficamos so 3 noites se pudessemos ficariamos mais... mas com certeza voltaremos...o lugar eh maravilhoso, quando chegamos f ... (572 characters truncated) ...  sem duvida recomendamos a hospedagem... Saimos bem contentes e satisfeitos do rio e ja estamos planejando a volta....  Nao percam a oportunidade!!! '),
 (1550596, 216700, datetime.date(2012, 6, 24), 2465739, 'Camila', "The apartment is located in the beautiful Laranjeiras neighborhood,  everything there is easy access. There' re bakeries, markets, banks, restaurants ... (862 characters truncated) ... me e bem comfortavel com uma linda sacada. \r<br/>\r<br/>Foi uma pena passarmos somente um dia na casa de Moara. Com certeza, voltaremos na sua casa."),
 (76744, 17878, datetime.date(2010, 8, 11), 10206, 'Mimi', "we had a really great experience staying in Max's apartment.  it was one block from copacabana beach with easy access to the local markets/shops.  Ma ... (42 characters truncated) ...  to send a list of suggestions on things to do.  I will refer friends to Max in the future if visiting Rio.  \r<br/>\r<br/>Thanks for everything Max!"),
 (91074, 17878, datetime.date(2010, 9, 6), 80253, 'Jan', 'Staying in Max appartment is like living in a cosy little French village and enyoing at te same time round the corner all the facilities that Rio has ... (99 characters truncated) ... c terrace, nicely decorated rooms, two spacious bedrooms, attentive doormen, and a host who really cares for his guests.  \r<br/>\r<br/>Jan & Iet    '),
 (137528, 17878, datetime.date(2010, 11, 12), 230449, 'Orene', 'In general very good and reasonable price.\r<br/>\r<br/>It is really great having local calls for free.It give an extra service to the apartment and  ... (313 characters truncated) ... zinha electricos sao um poco lentos para cozinhar)\r<br/>\r<br/>All the rest was correct, we will recommend the apart for other people.\r<br/>\r<br/>'),
 (147594, 17878, datetime.date(2010, 12, 1), 219338, 'David', 'The apt was nice and in a great location only a couple of blocks from the beach and shopping. Thanks for everything Max!'),
 (152368, 17878, datetime.date(2010, 12, 12), 266847, 'Armi', 'At Copacabana apartment is best the situation and BALCONY!\r<br/>Thanks Max (hope the door is fixed!)'),
 (155565, 17878, datetime.date(2010, 12, 19), 243287, 'Jonathan', 'A great apartment in a great location. The close proximity to transportation, supermarkets and everyday needs was really helpful. Max was very helpful and accommodating. '),
 (179219, 17878, datetime.date(2011, 2, 7), 172558, 'Anna', 'Apartment is exactly as Max advertised. If we had any issues, he immediately solved them. In addition, the terrace was a welcome addition. However, t ... (24 characters truncated) ...  dodgy. The neighbors would throw trash on the terrace which we had to toss out for them every day. Next time my friends and I will stay in Ipanema. '),
 (1147283, 326205, datetime.date(2012, 4, 18), 1705199, 'Daniela', 'Bob was really friendly and was always around!  The accomadations were not only clean but in a great location.  The apartment is in a safe neighborho ... (230 characters truncated) ... ncredibly nice to hang out during the evenings! Love it.  If ever I return to Rio, I will most certainly hope there is space in this apartment again!'),
 (186447, 17878, datetime.date(2011, 2, 22), 353604, 'Remy', 'Great apartment, amazing price and location in a pedestrianised street with a great atmosphere and large bedrooms, living room and balcony. The only  ... (15 characters truncated) ... e kitchen with two small electric hobs but we managed to get by and everything else more than made up for it. I would recommend this place to anyone!'),
 (191020, 17878, datetime.date(2011, 3, 1), 122909, 'Cliff', "Max was very organised and understanding to all our needs. He was very clear and honest with his apartment. The apartment was clean, safe and all the ... (104 characters truncated) ... ight when sleeping in a pretty safe neighbourhood. Strongly recommend Max's apartment and will stay here if I'm back in Rio again. Thanks Max!\r<br/>"),
 (204123, 17878, datetime.date(2011, 3, 20), 435996, 'Arfan', 'Amazing location,  great apartmen, tbest place i stayed in brazil, thanks Max x'),
 (213346, 17878, datetime.date(2011, 3, 30), 446854, 'Sandra', 'Appartement très bien situé, dans quartier calme.\r<br/>Les voisins ne sont pas bruyants.\r<br/>Appartement lumineux et spacieux.\r<br/>Max est arran ... (50 characters truncated) ... ses locataires.\r<br/>Nous avons passé un agréable séjour ! \r<br/>Rio est une ville magnifique et ses habitants très sympathiques.\r<br/>Merci Max !')]

In [25]:
df_listings_table = df_listings.head(100)
df_listings_table.to_sql('listings', con=engine, if_exists='append', index=False, method='multi')

100

In [26]:
%%sql
SELECT * FROM listings LIMIT 15;

 * postgresql://postgres:***@localhost:5432/postgres
15 rows affected.

[(17878, 'Condo in Rio de Janeiro · ★4.70 · 2 bedrooms · 2 beds · 1 bath', 68997, 'Matthias', None, 'Copacabana', Decimal('-22.965990'), Decimal('-43.179400'), 'Entire home/apt', Decimal('1357.00'), 5, 311, datetime.date(2023, 12, 22), Decimal('1.90'), 1, 269, 29, None),
 (216461, 'Rental unit in Rio de Janeiro · 1 bedroom · 1 bed · 1 bath', 1154263, 'Zeilma , Da', None, 'Flamengo', Decimal('-22.939900'), Decimal('-43.176760'), 'Private room', Decimal('734.00'), 1, 0, None, None, 1, 365, 0, None),
 (326205, 'Condo in Rio de Janeiro · ★4.57 · 1 bedroom · 1 bed · 1 bath', 1603206, 'Bob', None, 'Copacabana', Decimal('-22.968250'), Decimal('-43.182370'), 'Entire home/apt', Decimal('366.00'), 3, 152, datetime.date(2023, 11, 21), Decimal('1.07'), 5, 293, 14, None),
 (25026, 'Rental unit in Rio de Janeiro · ★4.72 · 1 bedroom · 1 bed · 1 bath', 102840, 'Viviane', None, 'Copacabana', Decimal('-22.977350'), Decimal('-43.191050'), 'Entire home/apt', Decimal('865.00'), 2, 275, datetime.date(2023, 12, 3), Decimal('1.67'), 1, 228, 29, None),
 (326575, 'Rental unit in Rio de Janeiro · ★4.81 · 2 bedrooms · 3 beds · 2 baths', 1668565, 'Maria José', None, 'Copacabana', Decimal('-22.976960'), Decimal('-43.189330'), 'Entire home/apt', Decimal('368.00'), 4, 227, datetime.date(2023, 11, 21), Decimal('1.58'), 1, 245, 12, None),
 (216700, 'Rental unit in Rio de Janeiro · ★4.96 · 1 bedroom · 1 bed · 1 shared bath', 1118486, 'Moara', None, 'Laranjeiras', Decimal('-22.943730'), Decimal('-43.191470'), 'Private room', Decimal('300.00'), 3, 24, datetime.date(2023, 11, 5), Decimal('0.17'), 2, 356, 3, None),
 (219250, 'Loft in Rio de Janeiro · ★4.82 · 1 bedroom · 2 beds · 1 bath', 1134264, 'Ricardo', None, 'Santa Teresa', Decimal('-22.916660'), Decimal('-43.179470'), 'Entire home/apt', Decimal('254.00'), 2, 431, datetime.date(2023, 12, 11), Decimal('3.07'), 2, 312, 25, None),
 (35764, 'Loft in Rio de Janeiro · ★4.90 · 1 bedroom · 1 bed · 1.5 baths', 153691, 'Patricia Miranda & Paulo', None, 'Copacabana', Decimal('-22.981070'), Decimal('-43.191360'), 'Entire home/apt', Decimal('373.00'), 3, 454, datetime.date(2023, 12, 17), Decimal('2.82'), 1, 62, 36, None),
 (220377, 'Rental unit in Rio de Janeiro · ★5.0 · 1 bedroom · 1 bed · 1 private bath', 1142424, 'Taciana', None, 'Tijuca', Decimal('-22.928800'), Decimal('-43.240460'), 'Private room', Decimal('220.00'), 1, 4, datetime.date(2017, 4, 6), Decimal('0.03'), 4, 294, 0, None),
 (327375, 'Rental unit in Rio de Janeiro · ★4.0 · 6 bedrooms · 16 beds · 5 baths', 1673501, 'Josy', None, 'Santa Teresa', Decimal('-22.921290'), Decimal('-43.181930'), 'Entire home/apt', Decimal('5874.00'), 3, 12, datetime.date(2020, 2, 25), Decimal('0.09'), 1, 365, 0, None),
 (41198, 'Rental unit in Rio de Janeiro · ★4.21 · 2 bedrooms · 1 bath', 178975, 'Nicky', None, 'Copacabana', Decimal('-22.981020'), Decimal('-43.191720'), 'Entire home/apt', Decimal('1701.00'), 3, 17, datetime.date(2016, 2, 9), Decimal('0.13'), 2, 44, 0, None),
 (48305, 'Rental unit in Ipanema · ★4.76 · 6 bedrooms · 7 beds · 7 baths', 70933, 'Goitaca', None, 'Ipanema', Decimal('-22.985910'), Decimal('-43.203020'), 'Entire home/apt', Decimal('6604.00'), 2, 163, datetime.date(2023, 12, 10), Decimal('1.04'), 10, 319, 36, None),
 (328626, 'Rental unit in Rio de Janeiro · 2 bedrooms · 5 beds · 3 baths', 1675497, 'Priscila', None, 'Santa Teresa', Decimal('-22.922860'), Decimal('-43.187900'), 'Entire home/apt', Decimal('1250.00'), 20, 1, datetime.date(2012, 2, 21), Decimal('0.01'), 1, 365, 0, None),
 (220705, 'Rental unit in Rio de Janeiro · 1 bedroom · 2 beds · 2.5 baths', 1144461, 'Rachel', None, 'Copacabana', Decimal('-22.982460'), Decimal('-43.193760'), 'Private room', Decimal('300.00'), 3, 0, None, None, 2, 0, 0, None),
 (223073, 'Loft in Rio de Janeiro · ★4.81 · 1 bedroom · 1 bed · 1 bath', 503995, '❤️ BrUx ❤️', None, 'Ipanema', Decimal('-22.982800'), Decimal('-43.204670'), 'Entire home/apt', Decimal('779.00'), 1, 463, datetime.date(2023, 12, 20), Decimal('3.11'), 7, 338, 26, None)]